#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=10:mem=80gb
#PBS -N humann3_healthy

set -euo pipefail 
IFS=$'\n\t' 

# --- Configuration ---
WORKDIR="${PBS_O_WORKDIR:-/rds/general/user/mteng/ephemeral/Project11-Nanopore-test/humann3}"
INPUT_DIR="healthy-fastq"
OUTPUT_DIR="humann3-output"
FASTQ_LIST="basename.txt"
THREADS=10

# --- Setup ---
cd "$WORKDIR" || { echo "FATAL ERROR: Failed to cd to $WORKDIR" >&2; exit 1; }

# Activate Conda environment
eval "$(~/anaconda3/bin/conda shell.bash hook)"
conda activate biobakery_env

mkdir -p "$OUTPUT_DIR"

# --- PBS ARRAY JOB CHECK ---
if [ -z "${PBS_ARRAY_INDEX:-}" ]; then
    echo "ERROR: PBS_ARRAY_INDEX is not set. Run this script using qsub -t 1-N." >&2
    exit 1
fi

# Get the base name (e.g., PFND111) from the list
BASE_NAME=$(awk -v idx="$PBS_ARRAY_INDEX" 'NR==idx{print; exit}' "$FASTQ_LIST")

if [ -z "$BASE_NAME" ]; then
    echo "ERROR: No input file entry found for index $PBS_ARRAY_INDEX in $FASTQ_LIST" >&2
    exit 1
fi

# --- bowtie2 decontamination --- #
INPUT_R1="${INPUT_DIR}/${BASE_NAME}_1.fastq.gz"
INPUT_R2="${INPUT_DIR}/${BASE_NAME}_2.fastq.gz"
HOST_DB="/rds/general/user/mteng/home/database/GRCh38_noalt_decoy_as"

if [ ! -f "$INPUT_R1" ] || [ ! -f "$INPUT_R2" ]; then
    echo "ERROR: Paired-end input files do not exist at: $INPUT_R1 and/or $INPUT_R2" >&2
    exit 1
fi

echo "--- Starting job for: ${BASE_NAME} (Index: $PBS_ARRAY_INDEX) ---"
echo "Reading paired-end files: $INPUT_R1 and $INPUT_R2"
echo "Using $THREADS threads for KneadData and HUMAnN3"

# Create sample-specific output directory
SAMPLE_OUTPUT_DIR="${OUTPUT_DIR}/${BASE_NAME}_humann3"
mkdir -p "$SAMPLE_OUTPUT_DIR" || { echo "ERROR: Failed to create output directory: $SAMPLE_OUTPUT_DIR" >&2; exit 1; }

# --- Run KneadData for QC and Host Decontamination ---
echo "Running KneadData for quality control and host decontamination..."

# KneadData will perform:
# 1. Trimming (Trimmomatic)
# 2. Host removal (Bowtie2)
# 3. Concatenation of all microbial reads (intact pairs, single orphans) into a single FASTQ file
#if kneaddata \
#    --input1 "$INPUT_R1" \
#    --input2 "$INPUT_R2" \
#    --output "$SAMPLE_OUTPUT_DIR" \
#    --reference-db "$HOST_DB" \
#    --output-prefix "${BASE_NAME}" \
#    --threads "$THREADS" \
#    --reorder \
#    --log "${SAMPLE_OUTPUT_DIR}/${BASE_NAME}_kneaddata.log"; then
#    echo "SUCCESS: KneadData analysis completed for ${BASE_NAME}."
#else
#    echo "CRITICAL ERROR: KneadData failed for ${BASE_NAME}. Check logs in: $SAMPLE_OUTPUT_DIR" >&2
#    exit 1
#fi

# --- Find the Concatenated Output File for HUMAnN3 ---
HUMANN3_INPUT_FILE="${SAMPLE_OUTPUT_DIR}/${BASE_NAME}_decontam_paired.fastq"

# --- Concatenate Decontaminated Reads --- 
cat "$SAMPLE_OUTPUT_DIR"/${BASE_NAME}_paired_1.fastq \
    "$SAMPLE_OUTPUT_DIR"/${BASE_NAME}_paired_2.fastq \
    "$SAMPLE_OUTPUT_DIR"/${BASE_NAME}_unmatched_1.fastq \
    "$SAMPLE_OUTPUT_DIR"/${BASE_NAME}_unmatched_2.fastq \
    > "$HUMANN3_INPUT_FILE"

if [ ! -s "$HUMANN3_INPUT_FILE" ]; then
    echo "ERROR: KneadData output file is missing or empty: $HUMANN3_INPUT_FILE" >&2
    exit 1
fi

# --- Run HUMAnN3 on Decontaminated Reads ---
echo "Running HUMAnN3 on decontaminated reads from: $HUMANN3_INPUT_FILE"

if humann \
    --input "$HUMANN3_INPUT_FILE" \
    --output "$SAMPLE_OUTPUT_DIR" \
    --threads "$THREADS"; then
    echo "SUCCESS: HUMAnN3 analysis completed for ${BASE_NAME}."
    echo "Final output saved to: $SAMPLE_OUTPUT_DIR"
    # OPTIONAL: Clean up intermediate files generated by KneadData 
    # (e.g., trimmed, host-mapped, paired, and unmatched files).
    # find "$SAMPLE_OUTPUT_DIR" -type f ! -name "*_concat.fastq" ! -name "*.log" ! -name "humann*" -delete 
else
    echo "CRITICAL ERROR: HUMAnN3 pipeline failed for ${BASE_NAME}. Check error logs in: $SAMPLE_OUTPUT_DIR" >&2
    exit 1
fi
